FROM python:3.11-slim

WORKDIR /app

RUN pip install docker

COPY api/requirements.txt .

RUN pip install --no-cache-dir --default-timeout=300 --retries 10 -r requirements.txt

COPY api/ .

EXPOSE 8000

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]