FROM python:3.11-slim

WORKDIR /app

RUN pip install docker

COPY requirements.txt .

RUN pip install --no-cache-dir --default-timeout=300 --retries 10 -r requirements.txt

COPY credit_risk_model.joblib /app/credit_risk_model.joblib

COPY . /app

EXPOSE 8000

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]